services:

  postgres:
    image: docker.io/library/postgres:18

    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: ${KEYCLOAK_DB_USER}
      POSTGRES_PASSWORD: ${KEYCLOAK_DB_PASSWORD}

    volumes:
      - postgres_data:/var/lib/postgresql

  keycloak:
    image: quay.io/keycloak/keycloak:26.2

    depends_on:
      - postgres

    command:
      - start-dev

    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: ${KEYCLOAK_ADMIN}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}

      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
      KC_DB_USERNAME: ${KEYCLOAK_DB_USER}
      KC_DB_PASSWORD: ${KEYCLOAK_DB_PASSWORD}

      KC_HOSTNAME: ${KEYCLOAK_HOSTNAME}

    ports:
      - "8080:8080"

volumes:
  postgres_data: